### ISSUE TITLE
Command-V is not working on macOS

### ISSUE THREAD

**Issue by aguang-xyz** [aguang-xyz/aurora-editor#30]
**Describe the bug**
Ctrl-V is not working on Mac OS.

**To Reproduce**
1. New document.
2. Copy some content into paste board.
3. Press Command-V in the editor. 

**Expected behaviour**
Content should be pasted

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.2.1

**Comment by ylz-at** [comment]
怎么自己给自己写issue...

**Comment by aguang-xyz** [comment]
@ylz-at 记录下还没时间修的bug 😅
