### ISSUE TITLE
File browser font not recognized on ubuntu

### ISSUE THREAD

**Issue by jcstange** [aguang-xyz/aurora-editor#32]
**Describe the bug**
Unable to see what I'm saving

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on save
![image](https://user-images.githubusercontent.com/20682665/116703537-132f6980-a9d3-11eb-8cd6-0a5d357ec088.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.2 LTS
 - Gnome version 3.36.8

**Comment by aguang-xyz** [comment]
@jcstange Hi there, it seems more likely some font packages are not installed on your system. BTW, the screenshot seems not really from my Aurora Editor? Which channel did you installed the editor?
