### ISSUE TITLE
Application freezes when blank control panel is opened

### ISSUE THREAD

**Issue by Unbearables** [aguang-xyz/aurora-editor#44]
**Describe the bug**
Everytime I open application and open control panel (File / View / Help) the application freezes with blank context menu - this freezes whole desktop GUI. This goes away after I try to open it multiple times (usually 3 times) and context menu from control panel is displayed correctly with proper items.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open application
2. Click on control panel
3. Blank context menu appears and application freezes
4. After while application recovers

**Expected behaviour**
Control panel is shown correctly and opened without freezing nor shutting down the app.

**Screenshots**
Frozen application (without blank context menu - I could not capture that screenshot as my desktop freezes) - in this case `File` tab is selected.
![image](https://user-images.githubusercontent.com/35105877/130202751-073b24e5-341f-459f-a578-0269760564cc.png)

**Desktop (please complete the following information):**
 - OS: Manjaro (AUR) - KDE Plasma
 - Version 5.13.11.-1-MANJARO (64-bit), KDE Plasma version: 5.22.4

**Additional context**
I downloaded the application from Snap store.
Logs from running application through console:
```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Gtk-Message: 10:08:10.507: Failed to load module "xapp-gtk3-module"
Gtk-Message: 10:08:10.532: Failed to load module "colorreload-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
Segmentation fault (core dumped)
```
Where `si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)` is displayed after application unfreezes.
BTW I can normally edit files before and after this bug appears.

**Comment by aguang-xyz** [comment]
Hi @Unbearables,

Thank you for the interest of using `Aurora Editor`. Honestly this app has only been tested under `Ubuntu & GNOME` environment.

Based on the logs, it is likely to be a compatibility issue with your AMD GPU Driver. Could you please follow this [guide](https://wiki.manjaro.org/index.php/Configure_Graphics_Cards#Automated_Identification_and_Installation) to reinstall Driver and see if it works first?

Cheers,
Grey W

**Comment by Unbearables** [comment]
Hello,
My graphics drivers are up to date:
```
NAME:        video-hybrid-amd-nvidia-prime
VERSION:     2021.07.28
```
Anyway, thx for the effort and good luck :)
