### ISSUE TITLE
Fail to use the app on Big Sur

### ISSUE THREAD

**Issue by ylz-at** [aguang-xyz/aurora-editor#48]
<img width="650" alt="Screen Shot 2021-09-23 at 1 40 20 PM" src="https://user-images.githubusercontent.com/8112071/134459431-1544448d-c296-41b5-9328-0ec54ae78d25.png">

**Comment by aguang-xyz** [comment]
@ylz-at The current release for macOS is not signed with a developer account (because I don't have one). You can click `Cancel` and go to `Preference -> Security Settings` and then choose `Open it anyway`.
